#!/bin/sh

# Get the branch name
branch=$(git rev-parse --symbolic --abbrev-ref HEAD)

echo "The branch is $branch"
# Check if the branch is 'main'
if [ "$branch" = "main" ]; then
    # Execute your script
    ./push_changes_to_instance.sh
fi
