# Use the official image as a parent image
FROM node:18

# Set the maintainer label
LABEL maintainer="leonhard.horstmeyer@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

ARG REACT_APP_DEVELOPMENT_MODE
ARG REACT_APP_DOCKERIZED

# Then, set them as environment variables so they are available during the build
ENV REACT_APP_DEVELOPMENT_MODE=$REACT_APP_DEVELOPMENT_MODE
ENV REACT_APP_DOCKERIZED=$REACT_APP_DOCKERIZED
# Set the working directory
WORKDIR /website

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the app
COPY . .

# Build the app
RUN yarn build:next:dev

# Expose the port the app runs on
EXPOSE 80

# Command to run the application
CMD ["yarn", "start:next:prod"]
