FROM node:18 AS build

WORKDIR /website

ARG REACT_APP_DEVELOPMENT_MODE
ARG REACT_APP_DOCKERIZED
ARG NEXT_PUBLIC_BACKEND_URL

ENV REACT_APP_DEVELOPMENT_MODE=$REACT_APP_DEVELOPMENT_MODE
ENV REACT_APP_DOCKERIZED=$REACT_APP_DOCKERIZED
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

COPY package.json yarn.lock ./
RUN corepack enable && yarn install --frozen-lockfile

COPY . .
RUN yarn build:static

FROM httpd:2.4-alpine

COPY --from=build /website/out/ /usr/local/apache2/htdocs/
COPY static-httpd.conf /usr/local/apache2/conf/extra/static-httpd.conf
RUN echo 'Include conf/extra/static-httpd.conf' >> /usr/local/apache2/conf/httpd.conf

EXPOSE 80
